
name: cib

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: seriesci bot
      run: |
        curl -L https://github.com/seriesci/cib/releases/download/v0.0.5/cib_0.0.5_Linux_x86_64.tar.gz | tar -xz
        ./cib
      env:
        SERIESCI_TOKEN: ${{ secrets.SERIESCI_TOKEN }}